title       : Храм Святителя Николая Мирликийского (в Отрадном)
description : Подворье Патриарха Московского и Всея Руси
author      : Во Славу Божию
url         : http://hramotradnoe.github.io

markdown    : kramdown

permalink   : /posts/:categories/:year/:month/:title/
exclude     :
  - LICENSE
  - README.md
