title       : Храм Святителя Николая Мирликийского (в Отрадном)
description : Подворье Патриарха Московского и Всея Руси
author      : Во Славу Божию
url         : http://hramotradnoe.github.io
# url         : http://localhost

permalink   : /posts/:categories/:year/:title/
exclude     :
  - LICENSE
  - README.md
