title       : Храм Святителя Николая Мирликийского (в Отрадном)
description	: Подворье Патриарха Московского и Всея Руси
author      : Во Славу Божию
url         : http://hramotradnoe.github.io

permalink   : /posts/:title
exclude     :
  - LICENSE
  - README.md
