title       : Храм Святителя Николая Мирликийского (в Отрадном)
description : Подворье Патриарха Московского и Всея Руси
author      : Во Славу Божию
url         : http://hramotradnoe.github.io
# url         : http://localhost

markdown    : redcarpet

redcarpet   :
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

permalink   : /posts/:categories/:year/:month/:title/
exclude     :
  - LICENSE
  - README.md
